FROM python:3.12-slim

# Install Poetry
ENV POETRY_VERSION=1.8.3 \
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR=/tmp/poetry_cache

RUN pip install --no-cache-dir poetry==$POETRY_VERSION

WORKDIR /app

# Install deps first (layer cache)
COPY pyproject.toml poetry.lock* ./
RUN poetry install --only main --no-root && rm -rf $POETRY_CACHE_DIR

COPY . .

RUN python manage.py migrate --run-syncdb

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
